# Default values for cita-cloud-local-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

kmsPassword: "123456"

pvcName: "local-pvc"

image:
  pullPolicy: IfNotPresent

service:
  nodePort: 30004

debug:
  enabled: true
  imageName: praqma/network-multitool
  imageTag: latest

sync:
  imageName: syncthing/syncthing
  imageTag: latest

network:
  imageName: citacloud/network_p2p
  imageTag: latest

consensus:
  imageName: citacloud/consensus_raft
  imageTag: latest

executor:
  imageName: citacloud/executor_evm
  imageTag: latest

stateDB:
  imageName: couchdb
  imageTag: latest

storage:
  imageName: citacloud/storage_rocksdb
  imageTag: latest

controller:
  imageName: citacloud/controller
  imageTag: latest

kms:
  imageName: citacloud/kms_sm
  imageTag: latest
