# Default values for cita-cloud-local-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Count of blockchain nodes.
replicaCount: 3

# pvcName -- Name of persistentVolumeClaim.
pvcName: "local-pvc"

config:
  # config.superAdmin -- Super admin account address.
  superAdmin: 0x415f568207900b6940477396fcd2c201efe49beb
  # config.imageTag -- Image tag of cita-cloud-config container.
  imageTag: latest
  # config.kmsPassword -- Password of kms.
  kmsPassword: "123456"
  # config.isStdout -- Is output log to stdout?
  isStdout: false
  # config.logLevel -- log level warn/info/debug/trace
  logLevel: info

image:
  # image.pullPolicy -- pullPolicy for all docker images.
  pullPolicy: Always

service:
  # service.nodePort -- nodePort to expose controller RPC.
  nodePort: 30004
  # service.vmPort -- vmPort expose executor RPC
  vmPort: 30005

debug:
  # debug.enabled -- Is there a debug container in each pod?
  enabled: true
  # debug.imageName -- Image name of debug container.
  imageName: praqma/network-multitool
  # debug.imageTag -- Image tag of debug container.
  imageTag: latest

network:
  # network.imageName -- docker image of network container. citacloud/network_p2p or citacloud/network_direct
  imageName: citacloud/network_p2p
  # network.imageTag -- Image tag of network container.
  imageTag: latest

consensus:
  # consensus.imageName -- docker image of consensus container. citacloud/consensus_raft or citacloud/consensus_bft
  imageName: citacloud/consensus_raft
  # consensus.imageTag -- Image tag of consensus container.
  imageTag: latest

executor:
  # executor.imageName -- docker image of executor container. citacloud/executor_evm or citacloud/executor_poc or citacloud/executor_chaincode_ext
  imageName: citacloud/executor_evm
  # executor.imageTag -- Image tag of executor container.
  imageTag: latest

stateDB:
  # stateDB.imageName -- docker image of stateDB container.
  imageName: couchdb
  # stateDB.imageTag -- Image tag of stateDB container.
  imageTag: latest

storage:
  # storage.imageName -- docker image of storage container. citacloud/storage_rocksdb or citacloud/storage_sqlite
  imageName: citacloud/storage_rocksdb
  # storage.imageTag -- Image tag of storage container.
  imageTag: latest

controller:
  # controller.imageName -- docker image of controller container.
  imageName: citacloud/controller
  # controller.imageTag -- Image tag of controller container.
  imageTag: latest

kms:
  # kms.imageName -- docker image of kms container. citacloud/kms_sm or citacloud/kms_eth
  imageName: citacloud/kms_sm
  # kms.imageTag -- Image tag of kms container.
  imageTag: latest
