apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "cita-cloud-local-cluster.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 50004
      targetPort: 50004
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cita-cloud-local-cluster.selectorLabels" . | nindent 4 }}
