apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless-service" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cita-cloud-local-cluster.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  selector: {{- include "cita-cloud-local-cluster.labels" . | nindent 4 }}
