apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "kms-secret-%s-%v" .Values.config.chainName .Values.config.nodeIndex }}
type: Opaque
data:
  key_file: {{ .Values.config.kmsPassword | b64enc | quote }}
